# 11、期约与异步函数七

## 1、期约(Promise)

### 1.1期约基础

> 1.期约状态机：期约的三种状态
>
> ​	a、待定
>
> ​	b、兑现
>
> ​	c、拒绝
>
> ​	注意： 期约的状态以经改变是不可逆转的，期约的状态是私有的外部是不可访问的。

````
创建 promise类
const p = new Promise(() => {})  注意必须传入一个值，不然会报错
基础使用 Promise类
const p1 = new Promise((resolvem, reject) =>{
    resolve()   // 执行成功异步
    reject() // 执行失败异步
}).then(res =>{
    console.log('成功')
}).catch(err => {
    console.log('失败')
})
````

> 2. Promise.resolve() 静态方法
>
>    1. resolve 是一个幂等方法(同种方法执行结果都一样)，幂等性会保留期约的状态
>
>    ````
>    let p = new Promise(() => {}); 
>    setTimeout(console.log, 0, p); // Promise <pending> 
>    setTimeout(console.log, 0, Promise.resolve(p)); // Promise <pending>
>    
>    setTimeout(console.log, 0, Promise.resolve(3)); // 3
>    ````
>
>    2. reosolve 的参数可以是任何值，错误对象也会进入成功状态。
>
>       ````
>       const p4 = Promise.resolve(new Error('foo'))
>       setTimeout(console.log, 0, p4)  //  Promise <resolved>: Error: foo
>       ````

> 3. Promise.reject()  方法
>
>    1. reject方法的错误信息不能被try{}catch{}捕获。
>
>    ````
>    let p = Promise.reject(3);
>    setTimeout(console.log, 0, p); // Promise <rejected>: 3
>    ````

> 4. 同步/异步执行的二元性 
>
>    ````
>    try { 
>     throw new Error('foo'); 
>    } catch(e) { 
>     console.log(e); // Error: foo 
>    } 
>    try { 
>    	 Promise.reject(new Error('bar'));  // 通过浏览器异步消息队列来处理的
>    } catch(e) {  //  并不能捕获到错误
>     	console.log(e); 
>    } 
>    // Uncaught (in promise) Error: bar
>    ````
>
>    **拒绝期约的错误并没有抛到执行同步代码的线程里，而是通过浏览器异步消息队 列来处理的。因此，try/catch 块并不能捕获该错误。代码一旦开始以异步模式执行，则唯一与之交互 的方式就是使用异步结构——更具体地说，就是期约的方法。**

### 1.2、期约的实例方法

> 1、Promise.prototype.then()方法
>
> ​	参数： onResolved处理程序，onRejected处理程序。注意：任何非函数类型的参数都会被静默掉。
>
> ​	返回值：返回**新**的期约实例
>
> ​	**onResolved处理程序：**	如果没有提供这个处理程序，则Promise.resolve() 就会包装上一个期约解决之后的值。如果没有实现的返回语句，则Promise.resolve()会包装默认的返回值undefined
>
> ````js
> let p1 = Promise.resolve('foo'); 
> // 若调用 then()时不传处理程序，则原样向后传
> let p2 = p1.then();
> setTimeout(console.log, 0, p2); // Promise <resolved>: foo
> 如果有显式的返回值，则 Promise.resolve()会包装这个值：
> let p6 = p1.then(() => 'bar'); 
> let p7 = p1.then(() => Promise.resolve('bar')); 
> 抛出异常会返回拒绝的期约：
> let p10 = p1.then(() => { throw 'baz'; }); 
> // Uncaught (in promise) baz 
> setTimeout(console.log, 0, p10); // Promise <rejected> baz
> setTimeout(console.log, 0, p6); // Promise <resolved>: bar
> // 异常返回rejected
> let p10 = p1.then(() => { throw 'baz'; }); 
> // Uncaught (in promise) baz 
> setTimeout(console.log, 0, p10); // Promise <rejected> baz
> 注意，返回错误值不会触发上面的拒绝行为，而会把错误对象包装在一个解决的期约中：
> let p11 = p1.then(() => Error('qux')); 
> setTimeout(console.log, 0, p11); // Promise <resolved>: Error: qux
> ````
>
> onRejected处理程序: 和nResolved处理程序处理一样。
>
> ````js
> let p1 = Promise.reject('foo');
> // 调用 then()时不传处理程序则原样向后传
> let p2 = p1.then();
> setTimeout(console.log, 0, p2); // Promise <rejected>: foo
> let p6 = p1.then(null, () => 'bar'); 
> let p7 = p1.then(null, () => Promise.resolve('bar')); 
> setTimeout(console.log, 0, p6); // Promise <resolved>: bar 
> setTimeout(console.log, 0, p7); // Promise <resolved>: bar
> ````

> 2、Promise.prototype.catch()
>
> ​	**catch其实是then的语法糖等价于Promise.prototype.then(null, onRejected)**
>
> ​	参数：onRejected处理程序
>
> ​	返回值：返回一个新的期约实例
>
>  ````js
> let p1 = new Promise(() => {}); 
> let p2 = p1.catch(); 
> setTimeout(console.log, 0, p1); // Promise <pending> 
> setTimeout(console.log, 0, p2); // Promise <pending> 
> setTimeout(console.log, 0, p1 === p2); // false
>  ````
>
> ​	在返回新期约实例方面，Promise.prototype.catch()的行为与 Promise.prototype.then()的 onRejected 处理程序是一样的。

> 3、Promise.prototype.finally()
>
> ​	参数：onFinally()
>
> ​	返回值:   返回一个新的期约实例（注意：待定或拒绝，其中之一满足以上的规则 ）
>
> ​	作用：onFinally处理程序不管期约的状态是解决还是拒绝都会执行finally，只用是用于处理免 onResolved 和 onRejected 处理程序中出 现冗余代码。
>
> ````js
> 这个新期约实例不同于 then()或 catch()方式返回的实例。因为 onFinally 被设计为一个状态
> 无关的方法，所以在大多数情况下它将表现为父期约的传递。对于已解决状态和被拒绝状态都是如此。
> let p1 = Promise.resolve('foo'); 
> // 这里都会原样后传
> let p2 = p1.finally(); 
> let p3 = p1.finally(() => undefined); 
> let p4 = p1.finally(() => {}); 
> let p5 = p1.finally(() => Promise.resolve()); 
> let p6 = p1.finally(() => 'bar'); 
> let p7 = p1.finally(() => Promise.resolve('bar')); 
> let p8 = p1.finally(() => Error('qux')); 
> setTimeout(console.log, 0, p2); // Promise <resolved>: foo 
> setTimeout(console.log, 0, p3); // Promise <resolved>: foo 
> setTimeout(console.log, 0, p4); // Promise <resolved>: foo 
> setTimeout(console.log, 0, p5); // Promise <resolved>: foo 
> setTimeout(console.log, 0, p6); // Promise <resolved>: foo 
> setTimeout(console.log, 0, p7); // Promise <resolved>: foo 
> setTimeout(console.log, 0, p8); // Promise <resolved>: foo
> 返回待定期约的情形并不常见，这是因为只要期约一解决，新期约仍然会原样后传初始的期约：
> let p1 = Promise.resolve('foo'); 
> // 忽略解决的值
> let p2 = p1.finally( 
>  () => new Promise((resolve, reject) => setTimeout(() => resolve('bar'), 100))); 
> setTimeout(console.log, 0, p2); // Promise <pending> 
> setTimeout(() => setTimeout(console.log, 0, p2), 200);
> ````

> 4、非重入期
>
> ​	**当期约进入落定状态时，与该状态相关的处理程序仅仅会被排期，而非立即执行。跟在添加这个处** 
>
> **理程序的代码之后的同步代码一定会在处理程序之前先执行。**
>
> ````
> // 创建解决的期约
> let p = Promise.resolve(); 
> // 添加解决处理程序
> // 直觉上，这个处理程序会等期约一解决就执行
> p.then(() => console.log('onResolved handler')); 
> // 同步输出，证明 then()已经返回
> console.log('then() returns'); 
> // 实际的输出：
> // then() returns 
> // onResolved handler
> ````

> 5、 邻近处理程序的执行顺序 
>
> ````js
> 如果给期约添加了多个处理程序，当期约状态变化时，相关处理程序会按照添加它们的顺序依次执行。无论是 then()、catch()还是 finally()添加的处理程序都是如此。
> let p1 = Promise.resolve(); 
> let p2 = Promise.reject(); 
> p1.then(() => setTimeout(console.log, 0, 1)); 
> p1.then(() => setTimeout(console.log, 0, 2)); 
> // 1 
> // 2 
> p2.then(null, () => setTimeout(console.log, 0, 3)); 
> p2.then(null, () => setTimeout(console.log, 0, 4)); 
> // 3 
> // 4 
> p2.catch(() => setTimeout(console.log, 0, 5)); 
> p2.catch(() => setTimeout(console.log, 0, 6)); 
> // 5 
> // 6 
> p1.finally(() => setTimeout(console.log, 0, 7)); 
> p1.finally(() => setTimeout(console.log, 0, 8)); 
> // 7 
> // 8
> ````

> 6、传递解决值和拒绝理由 
>
> `````js
> let p1 = new Promise((resolve, reject) => resolve('foo')); 
> p1.then((value) => console.log(value)); // foo 
> let p2 = new Promise((resolve, reject) => reject('bar')); 
> p2.catch((reason) => console.log(reason)); // bar 
> Promise.resolve()和 Promise.reject()在被调用时就会接收解决值和拒绝理由。同样地，它
> 们返回的期约也会像执行器一样把这些值传给 onResolved 或 onRejected 处理程序：
> let p1 = Promise.resolve('foo'); 
> p1.then((value) => console.log(value)); // foo 
> let p2 = Promise.reject('bar'); 
> p2.catch((reason) => console.log(reason)); // bar
> `````

> 7、拒绝期约与拒绝错误处理 
>
> 导致处理程序拒绝方式
>
> ````js
> let p1 = new Promise((resolve, reject) => reject(Error('foo'))); 
> let p2 = new Promise((resolve, reject) => { throw Error('foo'); }); 
> let p3 = Promise.resolve().then(() => { throw Error('foo'); }); 
> let p4 = Promise.reject(Error('foo')); 
> setTimeout(console.log, 0, p1); // Promise <rejected>: Error: foo 
> setTimeout(console.log, 0, p2); // Promise <rejected>: Error: foo 
> setTimeout(console.log, 0, p3); // Promise <rejected>: Error: foo 
> setTimeout(console.log, 0, p4); // Promise <rejected>: Error: foo
> ````

> 8、 拒绝期约与拒绝错误处理 
>
> > 注意：**异步错误只能通过异步的onRejected处理程序捕获。**
>
> `````js
> a、理由
> let p1 = new Promise((resolve, reject) => reject(Error('foo'))); 
> let p2 = new Promise((resolve, reject) => { throw Error('foo'); }); 
> let p3 = Promise.resolve().then(() => { throw Error('foo'); }); 
> let p4 = Promise.reject(Error('foo'));
> 
> b                                  ded;l;'.//catch。出发点都是捕获错误之
> 后将其隔离，同时不影响正常逻辑执行。为此，onRejected 处理程序的任务应该是在捕获异步错误之
> 后返回一个解决的期约。下面的例子中对比了同步错误处理与异步错误处理：
> console.log('begin synchronous execution'); 
> try { 
>  throw Error('foo'); 
> } catch(e) { 
>  console.log('caught error', e); 
> } 
> console.log('continue synchronous execution'); 
> // begin synchronous execution 
> // caught error Error: foo 
> // continue synchronous execution 
> 
> // 重点： onRejected 处理程序的任务应该是在捕获异步错误之后返回一个解决的期约
> new Promise((resolve, reject) => { 
>  console.log('begin asynchronous execution'); 
>  reject(Error('bar')); 
> }).catch((e) => { 
>  console.log('caught error', e); 
> }).then(() => { 
>  console.log('continue asynchronous execution'); 
> }); 
> // begin asynchronous execution 
> // caught error Error: bar 
> // continue asynchronous execution
> `````
>

### 1.3 期约连锁与期约合成

> 期约连锁：每个期约实例的方 法（then()、catch()和 finally()）都会返回一个新的期约对象，而这个新期约又有自己的实例方法。这样连缀方法调用就可以构成所谓的“期约连锁” 
>
> ````js
> let foo = function(str: string):Promise<any> {
>   console.log(str)
>   return new Promise((resolve, reject) => {
>     setTimeout(resolve, 1000)
>   })
> }
> 
> let p1 = new Promise((resolve, reject) => {
>   const res = '你好1'
>   console.log('last')
>   resolve(res)
> })
> 
> p1.then(res => foo('p1 executor'))
>   .then(res => foo('p2 executor'))
>   .then(res => foo('p3 executor'))
>   .then(res => foo('p4 executor'))
> ````

> 期约图：因为一个期约可以有任意多个处理程序，所以期约连锁可以构建有向非循环图的结构。这样，每个 期约都是图中的一个节点，而使用实例方法添加的处理程序则是有向顶点。因为图中的每个节点都会等 待前一个节点落定，所以图的方向就是期约的解决或拒绝顺序。
>
> 1、合成期约静态方法 : Promise.all()和Promise.race()
>
> Promise.all() // 合成期约所有被解决，才解决。
>
> ​	参数： 可迭代对象
>
> ​	返回值： 返回新期约
>
> ````js
> let p1 = Promise.all([ 
>  Promise.resolve(), 
>  Promise.resolve() 
> ]); 
> // 可迭代对象中的元素会通过 Promise.resolve()转换为期约
> let p2 = Promise.all([3, 4]); 
> // 空的可迭代对象等价于 Promise.resolve() 
> let p3 = Promise.all([]); 
> // 无效的语法
> let p4 = Promise.all(); 
> // TypeError: cannot read Symbol.iterator of undefined
> 
> 
> //合成的期约只会在每个包含的期约都解决之后才解决：
> let p = Promise.all([ 
>  Promise.resolve(), 
>  new Promise((resolve, reject) => setTimeout(resolve, 1000)) 
> ]); 
> setTimeout(console.log, 0, p); // Promise <pending> 
> p.then(() => setTimeout(console.log, 0, 'all() resolved!')); 
> // all() resolved!（大约 1 秒后）
> ````
>
> Promise.race()： 是一组集合中最先解决或拒绝的期约的镜像 
>
> ​	参数： 可迭代对象
>
> ​	返回值： 返回新期约
>
> ````js
> let p1 = Promise.race([ 
>  Promise.resolve(), 
>  Promise.resolve() 
> ]); 
> // 可迭代对象中的元素会通过 Promise.resolve()转换为期约
> let p2 = Promise.race([3, 4]); 
> // 空的可迭代对象等价于 new Promise(() => {}) 
> let p3 = Promise.race([]); 
> // 无效的语法
> let p4 = Promise.race(); 
> // TypeError: cannot read Symbol.iterator of undefined
> 
> // 解决先发生，超时后的拒绝被忽略
> let p1 = Promise.race([ 
>  Promise.resolve(3), 
>  new Promise((resolve, reject) => setTimeout(reject, 1000)) 
> ]); 
> setTimeout(console.log, 0, p1); // Promise <resolved>: 3 
> // 拒绝先发生，超时后的解决被忽略
> let p2 = Promise.race([ 
>  Promise.reject(4), 
>  new Promise((resolve, reject) => setTimeout(resolve, 1000)) 
> ]); 
> setTimeout(console.log, 0, p2); // Promise <rejected>: 4 
> // 迭代顺序决定了落定顺序
> let p3 = Promise.race([ 
>  Promise.resolve(5), 
>  Promise.resolve(6), 
>  Promise.resolve(7) 
> ]); 
> setTimeout(console.log, 0, p3); // Promise <resolved>: 5
> ````
>

> 2、串行期约合成
>
> 期约的异步产生值：异步产 生值并将其传给处理程序。基于后续期约使用之前期约的返回值来串联期约是期约的基本功能。 
>
> ````js
> // 普通写法
> function addTwo(x) {return x + 2;} 
> function addThree(x) {return x + 3;} 
> function addFive(x) {return x + 5;} 
> function addTen(x) { 
>  return Promise.resolve(x) 
>  .then(addTwo) 
>  .then(addThree) 
>  .then(addFive); 
> }
> addTen(8).then(console.log); // 18
> 
> // 使用 Array.prototype.reduce()可以写成更简洁的形式：
> function addTwo(x) {return x + 2;} 
> function addThree(x) {return x + 3;} 
> function addFive(x) {return x + 5;} 
> function addTen(x) { 
>  return [addTwo, addThree, addFive] 
>  .reduce((promise, fn) => promise.then(fn), Promise.resolve(x)); 
> } 
> addTen(8).then(console.log); // 18
> 
> // 封装写法
> function addTwo(x) {return x + 2;} 
> function addThree(x) {return x + 3;} 
> function addFive(x) {return x + 5;} 
> function compose(...fns) { 
>  return (x) => fns.reduce((promise, fn) => promise.then(fn), Promise.resolve(x)) 
> }
> let addTen = compose(addTwo, addThree, addFive);
> addTen(8).then(console.log); // 18
> ````

#### 1.4、期约扩展

> 1、期约取消
>
> ````js
> <button id="start">Start</button> 
> <button id="cancel">Cancel</button> 
> <script> 
> class CancelToken { 
>  constructor(cancelFn) { 
>  this.promise = new Promise((resolve, reject) => { 
>  cancelFn(() => { 
>  setTimeout(console.log, 0, "delay cancelled"); 
>  resolve(); 
>  }); 
>  }); 
>  } 
> } 
> const startButton = document.querySelector('#start'); 
> const cancelButton = document.querySelector('#cancel'); 
> 
> function cancellableDelayedResolve(delay) { 
>      setTimeout(console.log, 0, "set delay"); 
>      return new Promise((resolve, reject) => { 
>      const id = setTimeout((() => { 
>      setTimeout(console.log, 0, "delayed resolve"); 
>      resolve(); 
>      }), delay);
>     const cancelToken = new CancelToken((cancelCallback) => 
>      cancelButton.addEventListener("click", cancelCallback)); 
>      cancelToken.promise.then(() => clearTimeout(id)); 
>      }); 
> } 
> startButton.addEventListener("click", () => cancellableDelayedResolve(1000)); 
> </script>
> // 每次单击“Start”按钮都会开始计时，并实例化一个新的 CancelToken 的实例。此时，“Cancel”
> //按钮一旦被点击，就会触发令牌实例中的期约解决。而解决之后，单击“Start”按钮设置的超时也会被
> 取消。
> ````
>
> 2、 期约进度通知 
>
> 代码有误

## 2、异步函数

>​	ES8 的 async/await 旨在解决利用异步结构组织代码的问题。为此，ECMAScript 对函数进行了扩展， 为其增加了两个新关键字：async 和 await。

### 2.1、async

> 注释函数是一个异步函数 。（注意：没有await配合的时候和相当于同步函数）
>
> 返回值
>
> ​	返回一个期约
>
> ​	// 注意：async返回的是一个期约对象 对象里面的值就是异步函数的返回值 

### 2.2、await

> 1、阻止异步函数暂停和恢复执行的关键字。（异步函数的关键）
>
> ````js 
> function foo() {
>   return new Promise((resoleve) => {
>     setTimeout(() => {
>       console.log(2)
>       resoleve(1) // 成功状态
>     }, 1000)
>   })
> }
> 
> async function validate() {
>   console.log(1)
>   await foo()
>   console.log(3)
> }
> 
> // 1 2 3
> 
> function foo() {
>   return new Promise((resoleve) => {
>     setTimeout(() => {
>       console.log(2)
>     }, 1000)
>      resoleve(1) // 成功状态
>   })
> }
> 
> async function validate() {
>   console.log(1)
>   await foo()
>   console.log(3)
> }
> 
> // 1 3 2  上面代码不会暂停validate的执行 foo执行时promise的状态就由待定->解决，因此消息队列中取出解决 await 期约的处理程序
> ````
>
> 2、await 关键字期待（但实际上并不要求）一个实现 thenable 接口的对象，但常规的值也可以。如 
>
> 果是实现 thenable 接口的对象，则这个对象可以由 await 来“解包”。如果不是，则这个值就被当作 
>
> 已经解决的期约。下面的代码演示了这些情况：
>
> ````js
> // 等待一个原始值 
> async function foo() { 
>  console.log(await 'foo'); 
> } 
> foo(); 
> // foo
> // 等待一个没有实现 thenable 接口的对象
> async function bar() { 
>  console.log(await ['bar']); 
> } 
> bar(); 
> // ['bar']
> // 等待一个实现了 thenable 接口的非期约对象
> async function baz() { 
>  const thenable = { 
>  then(callback) { callback('baz'); } 
>  }; 
>  console.log(await thenable); 
> } 
> baz(); 
> // baz 
> // 等待一个期约
> async function qux() { 
>  console.log(await Promise.resolve('qux')); 
> } 
> qux(); 
> // qux
> ````
>

### 2.3、异步函数策略

> 1.实现sleep（）  
>
> 	> 作用： 延迟多少时间执行()
>
> `````
> async function sleep(delay: number) {
> 
>   return new Promise((resolve) => {
> 
>     setTimeout(resolve, delay);
> 
>   });
> }
> 
> async function foo() {
> 
>   const t0 = Date.now();
> 
>   await sleep(1500);
> 
>   console.log(Date.now() - t0);
> 
> }
> foo()
> `````

> 2、利用平行执行
>
> > 多个await时，让其平行顺序执行
>
> `````js
> a、如果使用 await 时不留心，则很可能错过平行加速的机会。来看下面的例子，其中顺序等待了 5
> 个随机的超时：
> async function randomDelay(id) { 
>  // 延迟 0~1000 毫秒
>  const delay = Math.random() * 1000; 
>  return new Promise((resolve) => setTimeout(() => { 
>  console.log(`${id} finished`); 
>  resolve(); 
>  }, delay)); 
> } 
> async function foo() { 
>  const t0 = Date.now(); 
>  for (let i = 0; i < 5; ++i) { 
>  await randomDelay(i); 
>  } 
>  console.log(`${Date.now() - t0}ms elapsed`); 
> } 
> foo(); 
> // 0 finished 
> // 1 finished 
> // 2 finished 
> // 3 finished 
> // 4 finished 
> // 877ms elapsed
> 
> // b、如果顺序不是必需保证的，那么可以先一次性初始化所有期约，然后再分别等待它们的结果。比如：
> async function randomDelay(id) { 
>  // 延迟 0~1000 毫秒
>  const delay = Math.random() * 1000; 
>  return new Promise((resolve) => setTimeout(() => { 
>  console.log(`${id} finished`); 
>  resolve(id); 
>  }, delay)); 
> } 
> async function foo() { 
>  const t0 = Date.now(); 
>  const promises = Array(5).fill(null).map((_, i) => randomDelay(i)); // 此时已经执行完 已经打印
>  for (const p of promises) { 
>  	console.log(`awaited ${await p}`);  // 此作用就是让代码按照顺序执行
>  } 
>  console.log(`${Date.now() - t0}ms elapsed`); 
> } 
> foo();
> `````

> 3、串行执行期约
>
> > 我们讨论过如何串行执行期约并把值传给后续的期约。使用 async/await，期约连锁会变 得很简单：
>
> ````js
> // 注意：async返回的是一个期约对象 对象里面的值就是异步函数的返回值
> async function addTwo(x: number): Promise<number> {
>   return x + 2
> }
> 
> async function addThree(x: number): Promise<number> {
>   return x + 3
> }
> 
> async function addFive(x: number): Promise<number> {
>   return x + 5
> }
> 
> async function addTen(x: number): Promise<number> {
>   for (const fn of [addTwo, addThree, addFive]) {
>     x = await fn(x)
>   }
>   return x
> }
> 
> addTen(9).then(console.log)
> ````
>
> 









